### ISSUE TITLE
Errors running convert under WSL Ubuntu 20

### ISSUE THREAD

**Issue by benjymous** [keithclark/ZzFXM#12]
```
$ bin/zzfxm-convert music.mod music.js
/usr/bin/env: ‘node --experimental-modules’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

```
$ node -v
v10.19.0
```

```
t$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

Changing the shebang in zzfxm-convert to 
```
#!/usr/bin/env -S node --experimental-modules
```

gets us a little further

```
$ bin/zzfxm-convert music.mod music.js
(node:1377) ExperimentalWarning: The ESM module loader is experimental.
/mnt/c/users/rich/code/ZzFXM/tools/convert/bin/zzfxm-convert:3
import '../cli.js';
       ^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at createDynamicModule (internal/modules/esm/translators.js:73:15)
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:40:9)
    at file:///mnt/c/users/rich/code/ZzFXM/tools/convert/bin/zzfxm-convert:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

changing it to ```import ('../cli.js');``` gets us further again

```
$ bin/zzfxm-convert ../music.mod ../music.js
(node:1455) ExperimentalWarning: The ESM module loader is experimental.
(node:1455) UnhandledPromiseRejectionWarning: /mnt/c/users/rich/code/ZzFXM/tools/convert/cli.js:1
import cli from 'cli';
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at createDynamicModule (internal/modules/esm/translators.js:73:15)
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:40:9)
    at file:///mnt/c/users/rich/code/ZzFXM/tools/convert/cli.js:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

but that's about where my understanding of anything fails me, and I begin to assume it must just be a local config error!

**Comment by keithclark** [comment]
Looks like a node version issue. From the errors it looks like Node is loading the modules as CJS, not ESM. Upgrading to latest node would help confirm that.

**Comment by benjymous** [comment]
Ok, looks like Ubuntu 20.04 is locked to an ancient version of node, so you need to force it to install something usable.

Now its upgraded, and I'm getting new error messages

```
$ node --version
v14.9.0

$ bin/zzfxm-convert music.mod music.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /home/benjymous/ZzFXM/tools/convert/bin/zzfxm-convert
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:101:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:31)
    at async Loader.import (internal/modules/esm/loader.js:164:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

Again seems to be to do with module import

Renaming to 

```zzfxm-convert.js``` seems to fix it, and actually converts (yay!)



so in summary:

- make sure running NodeJS 14
- fix the shebang
- rename the script to have a .js extension


Not sure if the shebang and extension should be a general fix, or just a note in the readme if anyone has problems.   Should probably also mention to make sure Node is newer than v10

**Comment by keithclark** [comment]
Great that you have it working. I'll look into those issues and push any fixes I find. Thanks for the report.

**Comment by keithclark** [comment]
I've just pushed an update to the convertor tool which may address some of these issues.
